apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node-nov15-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-nov15-test 
  name: node-nov15-test
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node-nov15-test 
